name = "IsingSolvers"
uuid = "19695d51-5812-4a2b-89b0-5195538873ee"
authors = ["pedromxavier <pedromxavier@psr-inc.com>"]
version = "0.1.0"

[deps]
Anneal = "e4d9eb7f-b088-426e-aeb5-1c0dae3d8abb"

[compat]
Anneal = "0.3.2"
julia = "1.6"